// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZMvOPMjZr5yWJIZ7kMJKBS679p2mLwAI',
    appId: '1:8278256171:web:2286e4071c38a01801d86e',
    messagingSenderId: '8278256171',
    projectId: 'tech-shift',
    authDomain: 'tech-shift.firebaseapp.com',
    storageBucket: 'tech-shift.appspot.com',
    measurementId: 'G-9Z63SCY79G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCz7YftKg9KGx2xoI1SujH3l9CGMInZTLg',
    appId: '1:8278256171:android:0236ee6ecb49c12401d86e',
    messagingSenderId: '8278256171',
    projectId: 'tech-shift',
    storageBucket: 'tech-shift.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBe9r74rV8lMaJk-5Ockx3BnWYWrFQEpdI',
    appId: '1:8278256171:ios:74093172b8bfb2a601d86e',
    messagingSenderId: '8278256171',
    projectId: 'tech-shift',
    storageBucket: 'tech-shift.appspot.com',
    androidClientId: '8278256171-p4i07t3coboimbolveicl0lt2simate8.apps.googleusercontent.com',
    iosClientId: '8278256171-c543gvpl88pd4nm4eb75ku7qpgimf0il.apps.googleusercontent.com',
    iosBundleId: 'com.example.prosample1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBe9r74rV8lMaJk-5Ockx3BnWYWrFQEpdI',
    appId: '1:8278256171:ios:1028dad70fc214fe01d86e',
    messagingSenderId: '8278256171',
    projectId: 'tech-shift',
    storageBucket: 'tech-shift.appspot.com',
    androidClientId: '8278256171-p4i07t3coboimbolveicl0lt2simate8.apps.googleusercontent.com',
    iosClientId: '8278256171-apoi239jnmagng7jf7b2o0kauh7gjct8.apps.googleusercontent.com',
    iosBundleId: 'com.example.prosample1.RunnerTests',
  );
}
